name: adamwrites
favicon: null
layout_spectrum: 0.4513061305042356
typography_spectrum: 0.0845411978662014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c2628'
    - '#3160ba'
    - '#bed0e6'
    - '#768d92'
    - '#fdfdfd'
  brandStrength: 0.25
  lightness: 0.12454799492843449
  saturation: 0.5698852234054357
  rhythmicContrast: 0.7902727583423257
purpose: []
